from crawlers.sites.academic import ACADEMIC_CRAWLERS, ACADEMIC_CRAWLER_MAP
from crawlers.sites.notice import NOTICE_CRAWLERS, NOTICE_CRAWLER_MAP

CRAWLER_MAP = {**NOTICE_CRAWLER_MAP, **ACADEMIC_CRAWLER_MAP}
CRAWLERS = [*NOTICE_CRAWLERS, *ACADEMIC_CRAWLERS]

__all__ = [
    "NOTICE_CRAWLERS",
    "ACADEMIC_CRAWLERS",
    "CRAWLERS",
    "CRAWLER_MAP",
]
