import { invoke } from "@tauri-apps/api/core";
import "./styles.css";
import "./auth.css";
import "./crawl.css";

type Runtime = { running:boolean; api_running:boolean; worker_running:boolean; url:string; admin_token:string; server_root:string; python_path:string; logs:string[]; show_dock_icon:boolean };
type McpTool = { name:string; public_name:string; description:string; group:string; enabled:boolean; input_schema:Record<string,unknown>; annotations:Record<string,boolean|null> };
type Notice = { id:number; title:string; source:string; category:string; posted_at:string|null; extraction_confidence:number|null; extraction_version:string|null; archived_at:string|null; storage_bytes:number };
type Asset = { id:number; kind:string; filename:string|null; source_url:string; storage_path:string|null; mime_type:string|null; extracted_text:string|null; extra?:any };
type Account = { id:number; username:string; email:string|null; student_id:string|null; name:string|null; major:string|null; year:number|null };
type CodexAccount = { id:string; label:string; email:string; account_id:string; active:boolean; added_at:string|null };

let runtime: Runtime;
let selectedNotice: number | null = null;
let codexLoginTimer: number | null = null;
let assetObjectUrls: string[] = [];
let activeCollectionSection: "crawl" | "model" = "crawl";
const app = document.querySelector<HTMLDivElement>("#app")!;

function h(value: unknown) { return String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!)); }
function formatBytes(value:unknown){const bytes=Math.max(0,Number(value)||0);if(bytes<1000)return `${bytes} B`;const units=["KB","MB","GB","TB"];let size=bytes/1000,index=0;while(size>=1000&&index<units.length-1){size/=1000;index+=1;}return `${size>=100?size.toFixed(0):size>=10?size.toFixed(1):size.toFixed(2)} ${units[index]}`;}
function richText(value:unknown){const raw=String(value??"");const pattern=/\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)|(https?:\/\/[^\s<]+)/g;let out="",last=0;for(const match of raw.matchAll(pattern)){const index=match.index??0;out+=h(raw.slice(last,index));const url=match[2]||match[3];const label=match[1]||url;out+=`<button class="text-link" data-external-url="${h(url)}">${h(label)}</button>`;last=index+match[0].length;}return out+h(raw.slice(last));}
function auth() { return { "Authorization": `Bearer ${runtime.admin_token}`, "Content-Type": "application/json" }; }
async function api(path:string, init:RequestInit={}) { let r:Response; try{r=await fetch(`${runtime.url}/api/admin${path}`, {...init, headers:{...auth(), ...(init.headers||{})}});}catch{throw new Error("KNU 서버에 연결할 수 없습니다. 대시보드에서 서버를 먼저 실행하세요.");} if(r.status===401)throw new Error("다른 KNU 서버 인스턴스가 실행 중입니다. 이전 Server Manager를 종료하고 대시보드에서 서버를 다시 시작하세요.");if(!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail); return r.json(); }
async function apiBlob(path:string){const r=await fetch(`${runtime.url}/api/admin${path}`,{headers:auth()});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail);return r.blob();}
function toast(message:string, error=false){ const el=document.createElement("div"); el.className=`toast ${error?"bad":""}`; el.textContent=message; document.body.append(el); setTimeout(()=>el.remove(),3200); }

function shell(){
  app.innerHTML=`<aside><div class="brand"><span class="mark">K</span><div><strong>KNU Server</strong><small>Independent Manager</small></div></div>
    <nav>${[["dashboard","대시보드"],["collection","수집 관리"],["data","데이터"],["tools","Tool"],["accounts","사용자 계정"],["logs","서버 로그"]].map(([id,n],i)=>`<button data-tab="${id}" class="${i?'':'active'}">${n}</button>`).join("")}</nav>
    <div class="aside-foot"><span id="dot" class="dot"></span><span id="aside-state">확인 중</span></div></aside><main><header><div><h1 id="title">대시보드</h1><p id="subtitle">KNU 플러그인 서버와 수집 상태를 관리합니다.</p></div><button id="refresh" class="ghost">새로고침</button></header><section id="view"></section></main>`;
  document.querySelectorAll<HTMLButtonElement>("nav button").forEach(b=>b.onclick=()=>openTab(b.dataset.tab!,b));
  document.querySelector<HTMLButtonElement>("#refresh")!.onclick=()=>openTab(document.querySelector<HTMLButtonElement>("nav button.active")!.dataset.tab!);
}
function setState(){ const on=runtime.running; document.querySelector("#dot")?.classList.toggle("on",on); const s=document.querySelector("#aside-state"); if(s)s.textContent=on?"서버 실행 중":"서버 중지됨"; }
const titles:Record<string,[string,string]>={dashboard:["대시보드","API와 크롤러 워커를 한 곳에서 시작하고 종료합니다."],collection:["수집 관리","공지 수집 범위·주기와 문서 분석 모델을 설정합니다."],data:["데이터","LLM이 실제 답변에 사용하는 저장 결과를 조회하고 검수합니다."],tools:["Tool","KNU MCP가 실제 공개하는 도구와 입력 규격을 확인합니다."],accounts:["사용자 계정","KNU 서비스 계정과 연결된 학적 정보를 관리합니다."],logs:["서버 로그","API와 worker 프로세스의 최근 출력을 확인합니다."]};
async function openTab(id:string, button?:HTMLButtonElement){ if(codexLoginTimer!==null){clearInterval(codexLoginTimer);codexLoginTimer=null;} document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active")); (button||document.querySelector(`[data-tab="${id}"]`))?.classList.add("active"); const [t,s]=titles[id]; document.querySelector("#title")!.textContent=t; document.querySelector("#subtitle")!.textContent=s; const view=document.querySelector<HTMLElement>("#view")!; view.innerHTML='<div class="loading">불러오는 중…</div>'; try { await ({dashboard,collection,data:notices,tools,accounts,logs} as Record<string,()=>Promise<void>>)[id](); } catch(e){ view.innerHTML=`<div class="empty error">${h(e)}</div>`; } }

async function refreshRuntime(){ runtime=await invoke<Runtime>("runtime_status"); setState(); }
async function dashboard(){ await refreshRuntime(); let status:any={}; if(runtime.running) status=await api("/status").catch(()=>({})); const v=document.querySelector("#view")!; v.innerHTML=`<div class="hero ${runtime.running?'healthy':''}"><div><span class="eyebrow">SYSTEM STATUS</span><h2>${runtime.running?'정상 실행 중':'서버가 중지되어 있습니다'}</h2><p>${runtime.running?h(runtime.url):'버튼 한 번으로 API와 크롤러 worker를 함께 시작합니다.'}</p></div><button id="power" class="power ${runtime.running?'stop':''}">${runtime.running?'서버 종료':'서버 실행'}</button></div><div class="stats"><article><span>저장 공지</span><strong>${status.notice_count??'—'}</strong></article><article><span>가입 계정</span><strong>${status.account_count??'—'}</strong></article><article><span>검토 필요</span><strong>${status.review_count??'—'}</strong></article></div><article class="panel"><h3>실행 구성</h3><dl><dt>API</dt><dd>${runtime.api_running?'실행 중':'중지'}</dd><dt>크롤러 Worker</dt><dd>${runtime.worker_running?'실행 중':'중지'}</dd><dt>Python</dt><dd>${h(runtime.python_path)}</dd><dt>서버 소스</dt><dd>${h(runtime.server_root)}</dd></dl><label class="check dock-setting"><input id="show-dock-icon" type="checkbox" ${runtime.show_dock_icon?'checked':''}/><span>macOS Dock에도 아이콘 표시<small>창을 닫아도 서버는 메뉴 막대에서 계속 실행됩니다.</small></span></label></article>`; document.querySelector<HTMLButtonElement>("#power")!.onclick=async()=>{ try{ await invoke(runtime.running?"stop_server":"start_server"); await new Promise(r=>setTimeout(r,700)); await dashboard(); }catch(e){toast(String(e),true);} }; document.querySelector<HTMLInputElement>("#show-dock-icon")!.onchange=async e=>{const show=(e.currentTarget as HTMLInputElement).checked;try{await invoke("set_show_dock_icon",{show});runtime.show_dock_icon=show;toast(show?"Dock 아이콘을 표시합니다.":"메뉴 막대 전용으로 전환했습니다.");}catch(error){toast(String(error),true)}}; }

async function tools(){
  const catalog=await api("/tools"); const items:McpTool[]=catalog.items||[]; const groups=[...new Set(items.map(item=>item.group))];
  const fields=(tool:McpTool)=>Object.keys((tool.input_schema as any)?.properties||{});
  document.querySelector("#view")!.innerHTML=`<article class="panel tool-summary"><div><span class="eyebrow">LIVE MCP CATALOG</span><h2>${h(catalog.server)}</h2><p class="muted">코드에 등록된 실제 MCP 도구를 직접 읽습니다. 별도 목록 파일을 관리하지 않습니다.</p></div><strong>${items.length}개</strong></article><div class="tool-groups">${groups.map(group=>`<section><div class="tool-group-head"><div><h3>${h(group)}</h3><p>${h(catalog.group_descriptions?.[group]||'')}</p></div><span>${items.filter(item=>item.group===group).length}개</span></div><div class="tool-grid">${items.filter(item=>item.group===group).map(tool=>`<article class="panel tool-card"><div class="list-head"><code>${h(tool.public_name)}</code><span class="tool-state ${tool.enabled?'on':''}">${tool.enabled?'공개 중':'비활성'}</span></div><p>${h(tool.description)}</p><div class="tool-badges"><span>${tool.annotations?.readOnlyHint?'읽기 전용':'쓰기 가능'}</span><span>${tool.annotations?.destructiveHint?'파괴적 변경 가능':'비파괴'}</span></div><details><summary>입력 인자 ${fields(tool).length}개</summary><pre>${h(JSON.stringify(tool.input_schema,null,2))}</pre></details></article>`).join('')}</div></section>`).join('')}</div><article class="panel note"><p>KNU Manager는 서버가 공개하는 도구 정의를 관리합니다. 각 Codmes Workspace에서 이 도구를 허용할지는 Codmes Server Manager의 Tool 메뉴에서 별도로 승인합니다.</p></article>`;
}
async function model(){
  const [s, accountData]=await Promise.all([api("/settings"), api("/auth/codex/accounts")]);
  const m=s.vlm; const codexAccounts:CodexAccount[]=accountData.items;
  document.querySelector("#view")!.innerHTML=`<article class="panel form"><h3>이미지 분석 모델</h3>
    <label>제공자<select id="provider"><option value="lmstudio">LM Studio (로컬)</option><option value="ollama">Ollama (로컬)</option><option value="openai-codex">OpenAI Codex (ChatGPT 계정)</option><option value="openai">OpenAI API (종량제)</option><option value="google">Gemini API (종량제)</option></select></label>
    <label>모델<div class="model-picker"><select id="model-select"><option value="">모델 목록을 불러오는 중…</option></select><button id="refresh-models" type="button" class="ghost">목록 새로고침</button></div><input id="model-name" value="${h(m.model)}" hidden/></label>
    <div id="generic-fields"><label>Base URL<input id="base-url" value="${h(m.base_url)}" placeholder="로컬 제공자 주소"/></label><label>API Key <small>${m.has_api_key?'저장된 키 있음 · 비우면 유지':'로컬 모델은 비워도 됨'}</small><input id="api-key" type="password" autocomplete="new-password"/></label></div>
    <div class="actions"><button id="test" class="ghost">연결 테스트</button><button id="save">저장</button></div><div id="model-result"></div></article>
    <article id="codex-auth" class="panel auth-panel"><div class="list-head"><div><h3>Codex 계정</h3><p class="muted">ChatGPT 계정으로 인증합니다. KNU Server에만 별도로 저장됩니다.</p></div><button id="codex-login">ChatGPT로 로그인</button></div><div id="login-state"></div><div id="codex-accounts">${codexAccountMarkup(codexAccounts)}</div></article>`;
  const provider=document.querySelector<HTMLSelectElement>("#provider")!; provider.value=m.provider;
  const modelInput=document.querySelector<HTMLInputElement>("#model-name")!; const modelSelect=document.querySelector<HTMLSelectElement>("#model-select")!;
  const baseInput=document.querySelector<HTMLInputElement>("#base-url")!; const apiKeyInput=document.querySelector<HTMLInputElement>("#api-key")!;
  const values=()=>({provider:provider.value,model:modelInput.value,base_url:baseInput.value,api_key:apiKeyInput.value||null});
  const refreshModels=async()=>{modelSelect.disabled=true;modelSelect.innerHTML='<option value="">모델 목록을 불러오는 중…</option>';try{const r=provider.value==="openai-codex"?await api("/auth/codex/models"):await api("/settings/models",{method:"POST",body:JSON.stringify(values())});setModelOptions(modelSelect,r.models,modelInput.value);document.querySelector("#model-result")!.textContent=`사용 가능한 모델 ${r.models.length}개`; }catch(e){modelSelect.innerHTML='<option value="">모델을 불러오지 못했습니다</option>';modelInput.value="";document.querySelector("#model-result")!.textContent=String(e);}finally{modelSelect.disabled=false;}};
  const updateProvider=async(changed=false)=>{const isCodex=provider.value==="openai-codex"; document.querySelector<HTMLElement>("#codex-auth")!.hidden=!isCodex; document.querySelector<HTMLElement>("#generic-fields")!.hidden=isCodex;if(changed){baseInput.value=provider.value==="ollama"?"http://127.0.0.1:11434/v1":provider.value==="lmstudio"?"http://127.0.0.1:1234/v1":"";modelInput.value="";}await refreshModels();};
  provider.onchange=()=>{void updateProvider(true)}; modelSelect.onchange=()=>{modelInput.value=modelSelect.value}; document.querySelector<HTMLButtonElement>("#refresh-models")!.onclick=()=>void refreshModels(); baseInput.onchange=()=>void refreshModels(); await updateProvider();
  document.querySelector<HTMLButtonElement>("#codex-login")!.onclick=startCodexLogin; bindCodexAccountButtons();
  document.querySelector<HTMLButtonElement>("#test")!.onclick=async()=>{try{const r=await api("/settings/test-vlm",{method:"POST",body:JSON.stringify(values())});setModelOptions(modelSelect,r.models,modelInput.value); document.querySelector("#model-result")!.textContent=`연결 성공 · 확인된 모델 ${r.models.length}개`;}catch(e){toast(String(e),true)}};
  document.querySelector<HTMLButtonElement>("#save")!.onclick=async()=>{if(provider.value==="openai-codex"&&!codexAccounts.length){toast("Codex 계정에 먼저 로그인하세요.",true);return;}if(!modelInput.value){toast("사용할 모델을 선택하세요.",true);return;}await api("/settings",{method:"PUT",body:JSON.stringify({crawl_enabled:s.crawl_enabled,crawl_interval_hours:s.crawl_interval_hours,vlm:values()})});toast("모델 설정을 저장했습니다.");};
}
function codexAccountMarkup(items:CodexAccount[]){return items.length?`<div class="account-grid">${items.map(a=>`<div class="account codex-account"><div><strong>${h(a.email||a.label)}</strong><span>${h(a.account_id||'계정 ID 없음')}</span></div><span class="account-status ${a.active?'active':''}">${a.active?'사용 중':'대기'}</span><button data-codex-select="${h(a.id)}" class="ghost" ${a.active?'disabled':''}>선택</button><button data-codex-remove="${h(a.id)}" class="danger">로그아웃</button></div>`).join('')}</div>`:'<div class="empty compact">Codex에 로그인된 계정이 없습니다.</div>'}
function bindCodexAccountButtons(){document.querySelectorAll<HTMLButtonElement>("[data-codex-select]").forEach(b=>b.onclick=async()=>{await api(`/auth/codex/accounts/${b.dataset.codexSelect}/select`,{method:"PUT"});toast("사용할 Codex 계정을 바꿨습니다.");collection('model')});document.querySelectorAll<HTMLButtonElement>("[data-codex-remove]").forEach(b=>b.onclick=async()=>{if(!confirm("이 장치의 KNU Server에서 Codex 계정을 로그아웃할까요?\nCodmes나 ChatGPT 계정은 영향받지 않습니다."))return;await api(`/auth/codex/accounts/${b.dataset.codexRemove}`,{method:"DELETE"});toast("계정을 로그아웃했습니다.");collection('model')});}
function setModelOptions(select:HTMLSelectElement,models:string[],current:string){select.innerHTML=models.map(x=>`<option value="${h(x)}">${h(x)}</option>`).join('');if(models.includes(current))select.value=current;else if(models.length){select.value=models[0];(document.querySelector("#model-name") as HTMLInputElement).value=models[0];}}
async function startCodexLogin(){try{const session=await api("/auth/codex/login",{method:"POST"});await invoke("open_auth_url",{url:session.verification_url});const state=document.querySelector("#login-state")!;state.innerHTML=`<div class="login-code"><div><span>브라우저에 아래 코드를 입력하세요</span><strong>${h(session.user_code)}</strong></div><button id="copy-code" class="ghost">코드 복사</button></div>`;document.querySelector<HTMLButtonElement>("#copy-code")!.onclick=async()=>{await navigator.clipboard.writeText(session.user_code);toast("코드를 복사했습니다.")};codexLoginTimer=window.setInterval(async()=>{try{const r=await api(`/auth/codex/login/${session.id}`);if(r.status==="approved"){clearInterval(codexLoginTimer!);codexLoginTimer=null;toast("Codex 로그인이 완료됐습니다.");collection('model')}else if(["error","expired","canceled"].includes(r.status)){clearInterval(codexLoginTimer!);codexLoginTimer=null;state.innerHTML=`<p class="error">${h(r.error||'로그인이 완료되지 않았습니다.')}</p>`;}}catch{}},Math.max(3000,session.interval*1000));}catch(e){toast(String(e),true)}}
async function collection(section: "crawl" | "model" = activeCollectionSection){activeCollectionSection=section;await (section==='crawl'?crawl():model());const view=document.querySelector<HTMLElement>("#view")!;view.insertAdjacentHTML('afterbegin',`<div class="section-tabs"><button data-collection-section="crawl" class="${section==='crawl'?'active':''}">수집 설정</button><button data-collection-section="model" class="${section==='model'?'active':''}">문서 분석 모델</button></div>`);view.querySelectorAll<HTMLButtonElement>("[data-collection-section]").forEach(button=>button.onclick=()=>void collection(button.dataset.collectionSection as "crawl"|"model"));}
async function notices(){
  const [filters,storage]=await Promise.all([api("/notices/filters"),api("/notices/storage")]);
  const option=(value:string,label:string)=>`<option value="${h(value)}">${h(label)}</option>`;
  document.querySelector("#view")!.innerHTML=`<div class="data-storage panel"><div><span>전체 저장 용량</span><strong>${formatBytes(storage.bytes)}</strong></div><small>공지 ${h(storage.notice_count)}건 · 자산 ${h(storage.asset_count)}개 · DB ${formatBytes(storage.database_bytes)} · 파일 ${formatBytes(storage.asset_file_bytes)}</small></div><div class="notice-filters panel"><div class="filter-grid"><label>공지 구분<select id="notice-source"><option value="">전체 공지</option>${filters.sources.map((x:any)=>option(x.code,x.name)).join('')}</select></label><label>카테고리<select id="notice-category"><option value="">전체 카테고리</option>${filters.categories.map((x:string)=>option(x,x)).join('')}</select></label><label class="date-filter">날짜<span class="date-range"><input id="notice-from" type="date" aria-label="시작일"/><i>–</i><input id="notice-to" type="date" aria-label="종료일"/></span></label><label>공지 상태<select id="notice-archive"><option value="all">전체</option><option value="active">현재 공지</option><option value="archived">과거 공지</option></select></label><label>추출 버전<select id="notice-version"><option value="">전체 버전</option>${filters.extraction_versions.map((x:string)=>option(x,x)).join('')}</select></label><label class="search-field">검색<input id="notice-search" placeholder="제목·본문 검색"/></label></div></div><div class="split"><article class="panel list"><div class="list-head"><h3 id="notice-count">공지</h3><button id="reset-notice-filters" class="ghost">필터 초기화</button></div><div id="notice-list"><div class="loading">불러오는 중…</div></div></article><article id="notice-detail" class="panel detail"><div class="empty">왼쪽에서 공지를 선택하세요.</div></article></div>`;
  const ids=['notice-source','notice-category','notice-from','notice-to','notice-archive','notice-version','notice-search'] as const;
  const inputs=Object.fromEntries(ids.map(id=>[id,document.querySelector<HTMLInputElement|HTMLSelectElement>(`#${id}`)!])) as Record<typeof ids[number],HTMLInputElement|HTMLSelectElement>;
  const row=(n:Notice)=>`<button data-notice="${n.id}"><strong>${h(n.title)}</strong><span>${h(n.source)} · ${h(n.posted_at||'날짜 없음')} · ${h(n.category)} · ${n.archived_at?'과거 공지':'현재 공지'} · 추출 ${h(n.extraction_version||'버전 없음')} · ${formatBytes(n.storage_bytes)}</span></button>`;
  const load=async()=>{const params=new URLSearchParams({limit:'100',q:inputs['notice-search'].value,source_code:inputs['notice-source'].value,category:inputs['notice-category'].value,archive:inputs['notice-archive'].value,extraction_version:inputs['notice-version'].value});if(inputs['notice-from'].value)params.set('date_from',inputs['notice-from'].value);if(inputs['notice-to'].value)params.set('date_to',inputs['notice-to'].value);const result=await api(`/notices?${params}`);document.querySelector("#notice-count")!.textContent=`공지 ${result.total}건`;const box=document.querySelector("#notice-list")!;box.innerHTML=result.items.length?result.items.map(row).join(''):'<div class="empty compact">조건에 맞는 공지가 없습니다.</div>';box.querySelectorAll<HTMLButtonElement>("[data-notice]").forEach(button=>button.onclick=()=>showNotice(Number(button.dataset.notice)));};
  let timer:number; Object.values(inputs).forEach(input=>{input.onchange=()=>void load();});inputs['notice-search'].oninput=()=>{clearTimeout(timer);timer=window.setTimeout(()=>void load(),250)};
  document.querySelector<HTMLButtonElement>("#reset-notice-filters")!.onclick=()=>{Object.values(inputs).forEach(input=>input.value='');inputs['notice-archive'].value='all';void load();};
  await load();
}
const documentInternalKinds=new Set(["attachment_hwp_structure","attachment_hwp_markdown","attachment_hwp_validation","attachment_hwp_image","attachment_hwp_binary","attachment_document_image","inline_image"]);
function attachmentMarkup(asset:Asset){return `<details><summary>${h(asset.filename||asset.kind)}</summary><pre>${h(asset.extracted_text||'추출 텍스트 없음')}</pre>${asset.source_url?`<button class="text-link" data-external-url="${h(asset.source_url)}">첨부 원본 열기</button>`:''}</details>`;}
function qualityMarkup(asset:Asset|undefined){if(!asset)return '<p class="muted">구조·품질 정보 없음</p>';try{const value=JSON.parse(asset.extracted_text||'{}');return `<dl class="quality-grid"><dt>판정</dt><dd>${h(value.status||'없음')}</dd><dt>품질 점수</dt><dd>${value.score==null?'없음':h(Math.round(Number(value.score)*1000)/10+'%')}</dd><dt>본문 일치도</dt><dd>${value.textTokenF1==null?'없음':h(Math.round(Number(value.textTokenF1)*1000)/10+'%')}</dd><dt>표</dt><dd>${h(value.tableCount??0)}개 · 셀 ${h(value.tableCellCount??0)}개</dd></dl>`;}catch{return `<pre>${h(asset.extracted_text||'품질 정보 없음')}</pre>`;}}
function documentAnalysisMarkup(assets:Asset[]){if(!assets.length)return '';const structure=assets.find(a=>a.kind==="attachment_hwp_structure");const markdown=assets.some(a=>a.kind==="attachment_hwp_markdown");const validation=assets.some(a=>a.kind==="attachment_hwp_validation");const images=assets.filter(a=>a.kind==="attachment_hwp_image"||a.kind==="attachment_document_image"||a.kind==="inline_image").sort((a,b)=>Number(a.extra?.figure?.number??999)-Number(b.extra?.figure?.number??999));const binaries=assets.filter(a=>a.kind==="attachment_hwp_binary");return `<details class="processing-results"><summary>본문·문서 그림 처리 상세 · 내부 파일 ${assets.length}개</summary><p class="muted">공지 본문과 HWP·HWPX·PDF·Word·Excel·PowerPoint의 검증된 그림 설명만 번호와 문맥을 포함해 검색에 사용합니다.</p>${structure?qualityMarkup(structure):''}${structure?`<div class="process-flags"><span>${markdown?'✓':'—'} 검색용 Markdown</span><span>${validation?'✓':'—'} HWPX 교차 검증</span></div>`:''}${images.length?`<h4>본문·문서 그림 ${images.length}개</h4><div class="asset-images">${images.map(a=>{const figure=a.extra?.figure;const analysis=a.extra?.analysis;const label=figure?.label||a.filename||'문서 내부 이미지';return `<figure><div class="asset-preview"><span>미리보기 불러오는 중…</span><img data-asset-preview="${a.id}" alt="${h(label)}"/></div><figcaption><strong>${h(label)} · ${h(a.filename)}</strong><span>${h(analysis?.description||'이미지 설명은 아직 생성되지 않았습니다.')}</span>${figure?.context?`<details class="image-context"><summary>문서 내 위치</summary><span>${h(figure.context)}</span></details>`:''}</figcaption></figure>`}).join('')}</div>`:''}${binaries.length?`<p class="muted">기타 내부 바이너리 ${binaries.length}개</p>`:''}</details>`;}
async function loadAssetPreviews(){await Promise.all([...document.querySelectorAll<HTMLImageElement>("[data-asset-preview]")].map(async img=>{try{const blob=await apiBlob(`/assets/${img.dataset.assetPreview}/content`);const url=URL.createObjectURL(blob);assetObjectUrls.push(url);img.src=url;img.onload=()=>img.parentElement?.classList.add("loaded");}catch{img.alt="이미지 미리보기를 불러오지 못했습니다.";img.parentElement?.classList.add("failed");}}));}
async function showNotice(id:number){ selectedNotice=id; assetObjectUrls.forEach(URL.revokeObjectURL);assetObjectUrls=[]; const n=await api(`/notices/${id}`);const assets:Asset[]=n.assets||[];const attachments=assets.filter(a=>!documentInternalKinds.has(a.kind));const internal=assets.filter(a=>documentInternalKinds.has(a.kind)); const el=document.querySelector("#notice-detail")!; el.innerHTML=`<span class="eyebrow">${h(n.source)} · ${h(n.category)}</span><h2>${h(n.title)}</h2><div class="metadata"><span>게시 ${h(n.posted_at)}</span><span>추출 버전 ${h(n.extraction_version||'없음')}</span><span>추출 신뢰도 ${n.extraction_confidence==null?'없음':Math.round(n.extraction_confidence*100)+'%'}</span><span>용량 ${formatBytes(n.storage_bytes)}</span><button id="open-original" class="text-link">원문</button></div><h3>저장된 본문</h3><div class="stored-body">${richText(n.body_content||n.content||'본문 없음')}</div><h3>첨부파일 ${attachments.length?attachments.length+'개':''}</h3>${attachments.length?attachments.map(attachmentMarkup).join(''):'<p class="muted">첨부 없음</p>'}${documentAnalysisMarkup(internal)}`; document.querySelector<HTMLButtonElement>("#open-original")!.onclick=()=>openExternal(n.url);document.querySelectorAll<HTMLButtonElement>("[data-external-url]").forEach(button=>button.onclick=()=>openExternal(button.dataset.externalUrl!));await loadAssetPreviews(); }
async function openExternal(url:string){try{await invoke("open_external_url",{url});}catch(error){toast(String(error),true)}}
async function accounts(){ const d=await api("/accounts"); document.querySelector("#view")!.innerHTML=`<article class="panel"><div class="list-head"><h3>가입 계정 ${d.items.length}개</h3><span class="muted">공식 포털 비밀번호는 저장하거나 변경하지 않습니다.</span></div><div class="account-grid">${d.items.map((a:Account)=>`<div class="account"><div><strong>${h(a.username)}</strong><span>${h(a.email||'이메일 없음')}</span></div><div><span>${h(a.student_id||'포털 미연결')}</span><span>${h(a.major||'학과 없음')} ${a.year?`${a.year}학년`:''}</span></div><button data-edit="${a.id}" class="ghost">수정</button><button data-delete="${a.id}" class="danger">삭제</button></div>`).join('')}</div></article>`; const map=new Map<number,Account>(d.items.map((a:Account)=>[a.id,a])); document.querySelectorAll<HTMLButtonElement>("[data-edit]").forEach(b=>b.onclick=()=>editAccount(map.get(Number(b.dataset.edit))!)); document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.delete);if(!confirm("KNU 서비스 계정을 삭제할까요? 공주대 공식 포털 계정은 삭제되지 않습니다."))return;const linked=confirm("연결된 학적·시간표·LMS 데이터도 함께 삭제할까요?\n취소를 누르면 서비스 계정만 삭제합니다.");await api(`/accounts/${id}?delete_linked_data=${linked}`,{method:"DELETE"});toast("계정을 삭제했습니다.");accounts();}); }
function editAccount(a:Account){ const dialog=document.createElement("dialog"); dialog.innerHTML=`<form method="dialog" class="form"><h3>계정 수정</h3>${[["username","사용자명",a.username],["email","이메일",a.email],["student_id","학번",a.student_id],["name","이름",a.name],["major","학과",a.major],["year","학년",a.year]].map(([id,l,v])=>`<label>${l}<input id="e-${id}" value="${h(v)}"/></label>`).join('')}<div class="actions"><button value="cancel" class="ghost">취소</button><button id="edit-save" value="default">저장</button></div></form>`;document.body.append(dialog);dialog.showModal();dialog.querySelector<HTMLButtonElement>("#edit-save")!.onclick=async e=>{e.preventDefault();const val=(id:string)=>(dialog.querySelector(`#e-${id}`) as HTMLInputElement).value||null;await api(`/accounts/${a.id}`,{method:"PUT",body:JSON.stringify({username:val("username"),email:val("email"),student_id:val("student_id"),name:val("name"),major:val("major"),year:val("year")?Number(val("year")):null})});dialog.close();dialog.remove();toast("계정을 수정했습니다.");accounts();};dialog.onclose=()=>dialog.remove(); }
async function logs(){ await refreshRuntime(); document.querySelector("#view")!.innerHTML=`<article class="panel"><div class="list-head"><h3>최근 로그</h3><button id="clear-logs" class="ghost">비우기</button></div><pre class="logs">${h(runtime.logs.join('\n')||'아직 로그가 없습니다.')}</pre></article>`; document.querySelector<HTMLButtonElement>("#clear-logs")!.onclick=async()=>{await invoke("clear_logs");logs();}; }

async function crawl(){
  const [s,state]=await Promise.all([api("/settings"),api("/crawl/status")]);
  const sources=s.capabilities?.crawl_sources||[]; const saved=s.crawl_request||{};
  const selectedSources=new Set(saved.source_codes?.length?saved.source_codes:sources.map((source:any)=>source.code));
  const locked=Boolean(s.crawl_enabled||state.active);
  document.querySelector("#view")!.innerHTML=`<article class="panel form crawl-settings"><div class="crawl-heading"><div><h3>수집 설정</h3><p class="muted">수동·자동 수집이 같은 범위와 소스, 추출 규칙을 사용합니다.</p></div><label class="toggle compact"><em>자동 수집</em><input id="crawl-enabled" type="checkbox" ${s.crawl_enabled?'checked':''}/><span></span><strong>${s.crawl_enabled?'ON':'OFF'}</strong></label></div><div class="crawl-state"><span>${state.active?'수집 중':s.crawl_enabled?'자동 수집 대기 중':'수동 수집 모드'}</span><strong>URL ${h(state.total)}개</strong><small>완료 ${h(state.completed)} · 수집 대기 ${h(state.discovered)} · 실패 ${h(state.failed)}</small></div>${locked?`<div class="crawl-lock">${s.crawl_enabled?'자동 수집이 켜져 있어 설정이 잠겼습니다. 수집 설정을 바꾸려면 자동 수집을 끄세요.':'현재 수집이 끝날 때까지 설정을 바꿀 수 없습니다.'}</div>`:''}<fieldset ${locked?'disabled':''}><label>수집 방식<select id="crawl-mode"><option value="all">전체 페이지</option><option value="range">지정 페이지 범위</option><option value="recent">최근 7일</option></select></label><div id="page-fields" class="page-fields"><label>시작 페이지<input id="start-page" type="number" min="1" value="${h(saved.start_page||1)}"/></label><label>끝 페이지<input id="end-page" type="number" min="1" value="${h(saved.end_page||saved.start_page||1)}"/></label></div><div><strong class="field-title">자동 수집 주기</strong><div class="segments">${[1,6,12,24].map(x=>`<button type="button" data-hours="${x}" class="${s.crawl_interval_hours===x?'selected':''}">${x===24?'1일':x+'시간'}</button>`).join('')}</div></div><label class="check refresh-version"><input id="refresh-extraction" type="checkbox" ${saved.refresh_outdated_extraction?'checked':''}/><span>이전 추출 버전도 ${h(s.capabilities?.current_extraction_version||'현재 버전')}로 갱신<small>체크하지 않으면 완료된 이전 버전 공지는 그대로 둡니다.</small></span></label><div><strong class="field-title">수집 소스</strong><div class="source-grid">${sources.map((source:any)=>`<label class="check"><input type="checkbox" data-source="${h(source.code)}" ${selectedSources.has(source.code)?'checked':''}/><span>${h(source.name)}${source.paged?'':' · 단일 문서'}</span></label>`).join('')}</div></div><p class="muted">목록의 고정 URL을 끝까지 대조하고, 완료된 URL의 상세·첨부는 생략합니다.</p><div class="actions"><button id="run-now">수집 시작</button></div></fieldset></article>`;
  let interval=s.crawl_interval_hours; const mode=document.querySelector<HTMLSelectElement>("#crawl-mode")!; const fields=document.querySelector<HTMLElement>("#page-fields")!; const start=document.querySelector<HTMLInputElement>("#start-page")!; const end=document.querySelector<HTMLInputElement>("#end-page")!;
  mode.value=saved.mode||'all'; const updatePageFields=()=>fields.hidden=mode.value!=='range'; mode.onchange=updatePageFields; updatePageFields();
  document.querySelectorAll<HTMLButtonElement>("[data-hours]").forEach(b=>b.onclick=()=>{interval=Number(b.dataset.hours);document.querySelectorAll("[data-hours]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});
  const request=()=>({mode:mode.value,start_page:Number(start.value),end_page:mode.value==='range'?Number(end.value):null,recent_days:7,refresh_outdated_extraction:document.querySelector<HTMLInputElement>("#refresh-extraction")!.checked,source_codes:[...document.querySelectorAll<HTMLInputElement>("[data-source]:checked")].map(x=>x.dataset.source!)});
  const save=async(crawl_enabled:boolean)=>api("/settings",{method:"PUT",body:JSON.stringify({crawl_enabled,crawl_interval_hours:interval,crawl_request:request(),vlm:{...s.vlm,api_key:null}})});
  const enabled=document.querySelector<HTMLInputElement>("#crawl-enabled")!; const enabledLabel=enabled.parentElement!.querySelector("strong")!; enabled.disabled=state.active&&!s.crawl_enabled;
  enabled.onchange=async()=>{const next=enabled.checked;enabled.disabled=true;try{if(next&&!request().source_codes.length)throw new Error("수집 소스를 하나 이상 선택하세요.");await save(next);enabledLabel.textContent=next?'ON':'OFF';toast(`자동 수집을 ${next?'켰습니다':'껐습니다'}.`);await crawl();}catch(e){enabled.checked=!next;toast(String(e),true);enabled.disabled=false;}};
  document.querySelector<HTMLButtonElement>("#run-now")!.onclick=async()=>{try{const value=request();if(!value.source_codes.length){toast("수집 소스를 하나 이상 선택하세요.",true);return;}await save(false);await api("/crawl/run",{method:"POST",body:JSON.stringify(value)});toast("공지 수집을 시작했습니다.");await crawl();}catch(e){toast(String(e),true)}};
}

shell(); refreshRuntime().then(()=>openTab("dashboard")); setInterval(()=>refreshRuntime().catch(()=>{}),4000);
