import { invoke } from "@tauri-apps/api/core";
import "./styles.css";
import "./auth.css";
import "./crawl.css";
import "./datasets.css";
import "./confirm.css";

type Runtime = { running:boolean; api_running:boolean; worker_running:boolean; database_running:boolean; redis_running:boolean; deployment_mode:"standalone"|"development"; data_root:string; url:string; admin_token:string; server_root:string; python_path:string; logs:string[]; show_dock_icon:boolean };
type McpTool = { name:string; public_name:string; description:string; group:string; enabled:boolean; input_schema:Record<string,unknown>; annotations:Record<string,boolean|null> };
type Notice = { id:number; title:string; source:string; category:string; posted_at:string|null; extraction_confidence:number|null; extraction_version:string|null; embedding_models:string[]; archived_at:string|null; storage_bytes:number };
type Asset = { id:number; kind:string; filename:string|null; source_url:string; storage_path:string|null; mime_type:string|null; extracted_text:string|null; extra?:any };
type Account = { id:number; username:string; email:string|null; student_id:string|null; name:string|null; major:string|null; year:number|null };
type CodexAccount = { id:string; label:string; email:string; account_id:string; active:boolean; added_at:string|null };

let runtime: Runtime;
let selectedNotice: number | null = null;
let codexLoginTimer: number | null = null;
let viewPollTimer: number | null = null;
let assetObjectUrls: string[] = [];
let activeCollectionSection: "crawl" | "model" = "crawl";
let activeNoticeSource = "";
let expandedProgressNotice = "";
const expandedProgressPages = new Set<string>();
const noticeFilterState={category:"",from:"",to:"",archive:"all",version:"",search:""};
const app = document.querySelector<HTMLDivElement>("#app")!;

function h(value: unknown) { return String(value ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!)); }
function formatBytes(value:unknown){const bytes=Math.max(0,Number(value)||0);if(bytes<1000)return `${bytes} B`;const units=["KB","MB","GB","TB"];let size=bytes/1000,index=0;while(size>=1000&&index<units.length-1){size/=1000;index+=1;}return `${size>=100?size.toFixed(0):size>=10?size.toFixed(1):size.toFixed(2)} ${units[index]}`;}
function richText(value:unknown){const raw=String(value??"");const pattern=/\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)|(https?:\/\/[^\s<]+)/g;let out="",last=0;for(const match of raw.matchAll(pattern)){const index=match.index??0;out+=h(raw.slice(last,index));const url=match[2]||match[3];const label=match[1]||url;out+=`<button class="text-link" data-external-url="${h(url)}">${h(label)}</button>`;last=index+match[0].length;}return out+h(raw.slice(last));}
function auth() { return { "Authorization": `Bearer ${runtime.admin_token}`, "Content-Type": "application/json" }; }
async function api(path:string, init:RequestInit={}) { let r:Response; try{r=await fetch(`${runtime.url}/api/admin${path}`, {...init, headers:{...auth(), ...(init.headers||{})}});}catch{throw new Error("KNU 서버에 연결할 수 없습니다. 대시보드에서 서버를 먼저 실행하세요.");} if(r.status===401)throw new Error("다른 KNU 서버 인스턴스가 실행 중입니다. 이전 Server Manager를 종료하고 대시보드에서 서버를 다시 시작하세요.");if(!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail); return r.json(); }
async function apiBlob(path:string){const r=await fetch(`${runtime.url}/api/admin${path}`,{headers:auth()});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail);return r.blob();}
function toast(message:string, error=false){ const el=document.createElement("div"); el.className=`toast ${error?"bad":""}`; el.textContent=message; document.body.append(el); setTimeout(()=>el.remove(),3200); }
function confirmAction(title:string,message:string,confirmLabel="확인"){return new Promise<boolean>(resolve=>{const dialog=document.createElement("dialog");dialog.innerHTML=`<div class="confirm-dialog"><h3>${h(title)}</h3><p>${h(message)}</p><div class="actions"><button type="button" class="ghost" data-confirm-cancel>취소</button><button type="button" class="danger" data-confirm-accept>${h(confirmLabel)}</button></div></div>`;document.body.append(dialog);let settled=false;const finish=(value:boolean)=>{if(settled)return;settled=true;dialog.close();dialog.remove();resolve(value)};dialog.querySelector<HTMLButtonElement>("[data-confirm-cancel]")!.onclick=()=>finish(false);dialog.querySelector<HTMLButtonElement>("[data-confirm-accept]")!.onclick=()=>finish(true);dialog.oncancel=e=>{e.preventDefault();finish(false)};dialog.showModal();});}
function stopViewPolling(){if(viewPollTimer!==null){window.clearTimeout(viewPollTimer);viewPollTimer=null;}}
function pollView(callback:()=>void,delay=1000){stopViewPolling();viewPollTimer=window.setTimeout(()=>{viewPollTimer=null;callback();},delay);}

function shell(){
  app.innerHTML=`<aside><div class="brand"><span class="mark">K</span><div><strong>KNU Server</strong><small>Independent Manager</small></div></div>
    <nav>${[["dashboard","대시보드"],["collection","수집 관리"],["data","데이터"],["tools","Tool"],["accounts","사용자 계정"],["logs","서버 로그"]].map(([id,n],i)=>`<button data-tab="${id}" class="${i?'':'active'}">${n}</button>`).join("")}</nav>
    <div class="aside-foot"><span id="dot" class="dot"></span><span id="aside-state">확인 중</span></div></aside><main><header><div><h1 id="title">대시보드</h1><p id="subtitle">KNU 플러그인 서버와 수집 상태를 관리합니다.</p></div><button id="refresh" class="ghost">새로고침</button></header><section id="view"></section></main>`;
  document.querySelectorAll<HTMLButtonElement>("nav button").forEach(b=>b.onclick=()=>openTab(b.dataset.tab!,b));
  document.querySelector<HTMLButtonElement>("#refresh")!.onclick=()=>openTab(document.querySelector<HTMLButtonElement>("nav button.active")!.dataset.tab!);
}
function setState(){ const on=runtime.running; document.querySelector("#dot")?.classList.toggle("on",on); const s=document.querySelector("#aside-state"); if(s)s.textContent=on?"서버 실행 중":"서버 중지됨"; }
const titles:Record<string,[string,string]>={dashboard:["대시보드","API와 크롤러 워커를 한 곳에서 시작하고 종료합니다."],collection:["수집 관리","공지 수집 범위·주기와 분석·임베딩 모델을 설정합니다."],data:["데이터","LLM이 실제 답변에 사용하는 저장 결과를 조회하고 검수합니다."],tools:["Tool","KNU MCP가 실제 공개하는 도구와 입력 규격을 확인합니다."],accounts:["사용자 계정","KNU 서비스 계정과 연결된 학적 정보를 관리합니다."],logs:["서버 로그","API와 worker 프로세스의 최근 출력을 확인합니다."]};
async function openTab(id:string, button?:HTMLButtonElement){ stopViewPolling(); if(codexLoginTimer!==null){clearInterval(codexLoginTimer);codexLoginTimer=null;} document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active")); (button||document.querySelector(`[data-tab="${id}"]`))?.classList.add("active"); const [t,s]=titles[id]; document.querySelector("#title")!.textContent=t; document.querySelector("#subtitle")!.textContent=s; const view=document.querySelector<HTMLElement>("#view")!; view.innerHTML='<div class="loading">불러오는 중…</div>'; try { await ({dashboard,collection,data:notices,tools,accounts,logs} as Record<string,()=>Promise<void>>)[id](); } catch(e){ view.innerHTML=`<div class="empty error">${h(e)}</div>`; } }

async function refreshRuntime(){ runtime=await invoke<Runtime>("runtime_status"); setState(); }
async function dashboard(){ await refreshRuntime(); let status:any={}; if(runtime.running) status=await api("/status").catch(()=>({})); const v=document.querySelector("#view")!; v.innerHTML=`<div class="hero ${runtime.running?'healthy':''}"><div><span class="eyebrow">SYSTEM STATUS</span><h2>${runtime.running?'정상 실행 중':'서버가 중지되어 있습니다'}</h2><p>${runtime.running?h(runtime.url):'버튼 한 번으로 DB·Redis·API·worker를 함께 시작합니다.'}</p></div><button id="power" class="power ${runtime.running?'stop':''}">${runtime.running?'서버 종료':'서버 실행'}</button></div><div class="stats"><article><span>저장 공지</span><strong>${status.notice_count??'—'}</strong></article><article><span>가입 계정</span><strong>${status.account_count??'—'}</strong></article><article><span>검토 필요</span><strong>${status.review_count??'—'}</strong></article></div><article class="panel"><h3>실행 구성</h3><dl><dt>배포 모드</dt><dd>${runtime.deployment_mode==='standalone'?'독립 실행형':'개발 환경'}</dd><dt>PostgreSQL</dt><dd>${runtime.deployment_mode==='development'?'외부 서비스':runtime.database_running?'실행 중':'중지'}</dd><dt>Redis</dt><dd>${runtime.deployment_mode==='development'?'외부 서비스':runtime.redis_running?'실행 중':'중지'}</dd><dt>API</dt><dd>${runtime.api_running?'실행 중':'중지'}</dd><dt>크롤러 Worker</dt><dd>${runtime.worker_running?'실행 중':'중지'}</dd><dt>영구 데이터</dt><dd>${h(runtime.data_root)}</dd><dt>Python</dt><dd>${h(runtime.python_path)}</dd><dt>서버 소스</dt><dd>${h(runtime.server_root)}</dd></dl><label class="check dock-setting"><input id="show-dock-icon" type="checkbox" ${runtime.show_dock_icon?'checked':''}/><span>macOS Dock에도 아이콘 표시<small>창을 닫아도 서버는 메뉴 막대에서 계속 실행됩니다.</small></span></label></article>`; document.querySelector<HTMLButtonElement>("#power")!.onclick=async()=>{ try{ await invoke(runtime.running?"stop_server":"start_server"); await new Promise(r=>setTimeout(r,700)); await dashboard(); }catch(e){toast(String(e),true);} }; document.querySelector<HTMLInputElement>("#show-dock-icon")!.onchange=async e=>{const show=(e.currentTarget as HTMLInputElement).checked;try{await invoke("set_show_dock_icon",{show});runtime.show_dock_icon=show;toast(show?"Dock 아이콘을 표시합니다.":"메뉴 막대 전용으로 전환했습니다.");}catch(error){toast(String(error),true)}}; }

async function tools(){
  const catalog=await api("/tools"); const items:McpTool[]=catalog.items||[]; const groups=[...new Set(items.map(item=>item.group))];
  const fields=(tool:McpTool)=>Object.keys((tool.input_schema as any)?.properties||{});
  document.querySelector("#view")!.innerHTML=`<article class="panel tool-summary"><div><span class="eyebrow">LIVE MCP CATALOG</span><h2>${h(catalog.server)}</h2><p class="muted">코드에 등록된 실제 MCP 도구를 직접 읽습니다. 별도 목록 파일을 관리하지 않습니다.</p></div><strong>${items.length}개</strong></article><div class="tool-groups">${groups.map(group=>`<section><div class="tool-group-head"><div><h3>${h(group)}</h3><p>${h(catalog.group_descriptions?.[group]||'')}</p></div><span>${items.filter(item=>item.group===group).length}개</span></div><div class="tool-grid">${items.filter(item=>item.group===group).map(tool=>`<article class="panel tool-card"><div class="list-head"><code>${h(tool.public_name)}</code><span class="tool-state ${tool.enabled?'on':''}">${tool.enabled?'공개 중':'비활성'}</span></div><p>${h(tool.description)}</p><div class="tool-badges"><span>${tool.annotations?.readOnlyHint?'읽기 전용':'쓰기 가능'}</span><span>${tool.annotations?.destructiveHint?'파괴적 변경 가능':'비파괴'}</span></div><details><summary>입력 인자 ${fields(tool).length}개</summary><pre>${h(JSON.stringify(tool.input_schema,null,2))}</pre></details></article>`).join('')}</div></section>`).join('')}</div><article class="panel note"><p>KNU Manager는 서버가 공개하는 도구 정의를 관리합니다. 각 Codmes Workspace에서 이 도구를 허용할지는 Codmes Server Manager의 Tool 메뉴에서 별도로 승인합니다.</p></article>`;
}
function embeddingDatasetMarkup(items:any[]){const labels:Record<string,string>={ready:"준비 완료",building:"생성 중",stale:"동기화 필요",failed:"실패"};return items.length?`<div class="embedding-datasets">${items.map(d=>`<div class="embedding-dataset ${d.active?'active':''}"><div><div class="dataset-title"><strong>${h(d.provider)} · ${h(d.model)}</strong><span class="dataset-state ${h(d.status)}">${d.active?'사용 중':labels[d.status]||d.status}</span></div><small>${h(d.dimension)}차원 · ${d.search_mode==='hnsw'?'HNSW 빠른 검색':'정확 검색'} · 공지 ${h(d.completed_notices)} / ${h(d.total_notices)} · 청크 ${h(d.total_chunks)} · ${formatBytes(d.bytes)}</small>${d.error?`<p class="error">${h(d.error)}</p>`:''}${d.status==='building'?`<div class="dataset-progress"><i style="width:${d.total_notices?Math.round(d.completed_notices/d.total_notices*100):0}%"></i></div>`:''}</div><div class="dataset-actions">${!d.active&&d.status==='ready'?`<button data-dataset-activate="${d.id}" class="ghost">사용하기</button>`:''}${!d.active&&d.status!=='building'?`<button data-dataset-sync="${d.id}" class="ghost">${d.status==='stale'?'동기화':'다시 생성'}</button>`:''}${!d.active&&d.status!=='building'?`<button data-dataset-delete="${d.id}" data-dataset-name="${h(d.model)}" class="danger">삭제</button>`:''}</div></div>`).join('')}</div>`:'<div class="empty compact">보관된 임베딩 데이터셋이 없습니다.</div>'}
async function model(){
  const [s, accountData, rebuild,datasetData]=await Promise.all([api("/settings"), api("/auth/codex/accounts"),api("/settings/rebuild-embedding"),api("/settings/embedding-datasets")]);
  const m=s.vlm; const em=s.embedding; const codexAccounts:CodexAccount[]=accountData.items;
  document.querySelector("#view")!.innerHTML=`<article class="panel form"><h3>이미지 분석 모델</h3>
    <label>제공자<select id="provider"><option value="lmstudio">LM Studio (로컬)</option><option value="ollama">Ollama (로컬)</option><option value="openai-codex">OpenAI Codex (ChatGPT 계정)</option><option value="openai">OpenAI API (종량제)</option><option value="google">Gemini API (종량제)</option></select></label>
    <label>모델<div class="model-picker"><select id="model-select"><option value="">모델 목록을 불러오는 중…</option></select><button id="refresh-models" type="button" class="ghost">목록 새로고침</button></div><input id="model-name" value="${h(m.model)}" hidden/></label>
    <div id="generic-fields"><label>Base URL<input id="base-url" value="${h(m.base_url)}" placeholder="로컬 제공자 주소"/></label><label>API Key <small>${m.has_api_key?'저장된 키 있음 · 비우면 유지':'로컬 모델은 비워도 됨'}</small><input id="api-key" type="password" autocomplete="new-password"/></label></div>
    <div class="actions"><button id="test" class="ghost">연결 테스트</button><button id="save">저장</button></div><div id="model-result"></div></article>
    <article id="codex-auth" class="panel auth-panel"><div class="list-head"><div><h3>Codex 계정</h3><p class="muted">ChatGPT 계정으로 인증합니다. KNU Server에만 별도로 저장됩니다.</p></div><button id="codex-login">ChatGPT로 로그인</button></div><div id="login-state"></div><div id="codex-accounts">${codexAccountMarkup(codexAccounts)}</div></article>
    <article class="panel form"><h3>임베딩 모델</h3><p class="muted">현재 검색 모델은 <strong>${h(em.provider)} · ${h(em.model)}</strong> (${h(em.dimension)}차원)입니다. 교체 중에도 기존 모델로 검색하며, 새 임베딩이 모두 준비된 뒤 한 번에 전환합니다.</p>
    <label>제공자<select id="embedding-provider"><option value="ollama">Ollama (로컬)</option><option value="lmstudio">LM Studio (로컬)</option><option value="openai">OpenAI API (종량제)</option><option value="google">Gemini API (종량제)</option></select></label>
    <label>모델<div class="model-picker"><select id="embedding-model-select"><option value="">모델 목록을 불러오는 중…</option></select><button id="refresh-embedding-models" type="button" class="ghost">목록 새로고침</button></div><input id="embedding-model-name" value="${h(em.model)}" hidden/></label>
    <label>출력 차원 <small id="embedding-dimension-help">Ollama 모델의 embedding length를 확인합니다.</small><select id="embedding-dimension"><option value="${h(em.dimension)}">${h(em.dimension)}차원</option></select><input id="embedding-dimension-custom" type="number" min="1" max="4096" value="${h(em.dimension)}" hidden/></label>
    <label>Base URL<input id="embedding-base-url" value="${h(em.base_url)}" placeholder="로컬 제공자 주소"/></label><label>API Key <small>${em.has_api_key?'저장된 키 있음 · 비우면 유지':'Ollama는 비워도 됨'}</small><input id="embedding-api-key" type="password" autocomplete="new-password"/></label>
    <div class="actions"><button id="test-embedding" class="ghost">연결 테스트</button><button id="replace-embedding">데이터셋 생성 후 교체</button></div><div id="embedding-result">${rebuild.state==='running'?`새 데이터셋 생성 중 ${h(rebuild.completed)} / ${h(rebuild.total)}`:rebuild.state==='failed'?`이전 생성 실패 · ${h(rebuild.error)}`:''}</div></article>
    <article class="panel embedding-library"><div class="list-head"><div><h3>보관된 임베딩 데이터셋</h3><p class="muted">완료된 모델은 즉시 전환할 수 있고, 사용하지 않는 데이터는 별도로 삭제할 수 있습니다.</p></div></div>${embeddingDatasetMarkup(datasetData.items||[])}</article>`;
  const provider=document.querySelector<HTMLSelectElement>("#provider")!; provider.value=m.provider;
  const modelInput=document.querySelector<HTMLInputElement>("#model-name")!; const modelSelect=document.querySelector<HTMLSelectElement>("#model-select")!;
  const baseInput=document.querySelector<HTMLInputElement>("#base-url")!; const apiKeyInput=document.querySelector<HTMLInputElement>("#api-key")!;
  const values=()=>({provider:provider.value,model:modelInput.value,base_url:baseInput.value,api_key:apiKeyInput.value||null});
  const refreshModels=async()=>{modelSelect.disabled=true;modelSelect.innerHTML='<option value="">모델 목록을 불러오는 중…</option>';try{const r=provider.value==="openai-codex"?await api("/auth/codex/models"):await api("/settings/models",{method:"POST",body:JSON.stringify(values())});setModelOptions(modelSelect,r.models,modelInput.value);document.querySelector("#model-result")!.textContent=`사용 가능한 모델 ${r.models.length}개`; }catch(e){modelSelect.innerHTML='<option value="">모델을 불러오지 못했습니다</option>';modelInput.value="";document.querySelector("#model-result")!.textContent=String(e);}finally{modelSelect.disabled=false;}};
  const updateProvider=async(changed=false)=>{const isCodex=provider.value==="openai-codex"; document.querySelector<HTMLElement>("#codex-auth")!.hidden=!isCodex; document.querySelector<HTMLElement>("#generic-fields")!.hidden=isCodex;if(changed){baseInput.value=provider.value==="ollama"?"http://127.0.0.1:11434/v1":provider.value==="lmstudio"?"http://127.0.0.1:1234/v1":"";modelInput.value="";}await refreshModels();};
  provider.onchange=()=>{void updateProvider(true)}; modelSelect.onchange=()=>{modelInput.value=modelSelect.value}; document.querySelector<HTMLButtonElement>("#refresh-models")!.onclick=()=>void refreshModels(); baseInput.onchange=()=>void refreshModels(); await updateProvider();
  document.querySelector<HTMLButtonElement>("#codex-login")!.onclick=startCodexLogin; bindCodexAccountButtons();
  document.querySelector<HTMLButtonElement>("#test")!.onclick=async()=>{try{const r=await api("/settings/test-vlm",{method:"POST",body:JSON.stringify(values())});setModelOptions(modelSelect,r.models,modelInput.value); document.querySelector("#model-result")!.textContent=`연결 성공 · 확인된 모델 ${r.models.length}개`;}catch(e){toast(String(e),true)}};
  document.querySelector<HTMLButtonElement>("#save")!.onclick=async()=>{if(provider.value==="openai-codex"&&!codexAccounts.length){toast("Codex 계정에 먼저 로그인하세요.",true);return;}if(!modelInput.value){toast("사용할 모델을 선택하세요.",true);return;}await api("/settings",{method:"PUT",body:JSON.stringify({crawl_enabled:s.crawl_enabled,crawl_interval_hours:s.crawl_interval_hours,vlm:values()})});toast("모델 설정을 저장했습니다.");};
  const embeddingProvider=document.querySelector<HTMLSelectElement>("#embedding-provider")!;embeddingProvider.value=em.provider;
  const embeddingModel=document.querySelector<HTMLInputElement>("#embedding-model-name")!;const embeddingSelect=document.querySelector<HTMLSelectElement>("#embedding-model-select")!;
  const embeddingBase=document.querySelector<HTMLInputElement>("#embedding-base-url")!;const embeddingKey=document.querySelector<HTMLInputElement>("#embedding-api-key")!;const embeddingDimension=document.querySelector<HTMLSelectElement>("#embedding-dimension")!;const embeddingDimensionCustom=document.querySelector<HTMLInputElement>("#embedding-dimension-custom")!;const embeddingDimensionHelp=document.querySelector<HTMLElement>("#embedding-dimension-help")!;const embeddingResult=document.querySelector<HTMLElement>("#embedding-result")!;
  const selectedEmbeddingDimension=()=>Number(embeddingProvider.value==="ollama"?embeddingDimension.value:embeddingDimensionCustom.value);
  const embeddingValues=()=>({provider:embeddingProvider.value,model:embeddingModel.value,base_url:embeddingBase.value,dimension:selectedEmbeddingDimension(),api_key:embeddingKey.value||null});
  const dimensionOptions=(nativeDimension:number)=>{const result:number[]=[];for(let value=512;value<nativeDimension;value*=2)result.push(value);result.push(nativeDimension);return [...new Set(result)].filter(value=>value>=1&&value<=nativeDimension).sort((a,b)=>a-b)};
  const refreshEmbeddingDimension=async(useNative=false)=>{if(embeddingProvider.value!=="ollama"){embeddingDimension.hidden=true;embeddingDimensionCustom.hidden=false;embeddingDimensionHelp.textContent="이 제공자는 차원 메타데이터를 자동으로 제공하지 않아 직접 입력합니다.";return;}embeddingDimension.hidden=false;embeddingDimensionCustom.hidden=true;if(!embeddingModel.value)return;embeddingDimension.disabled=true;embeddingDimensionHelp.textContent="Ollama에서 embedding length를 확인하는 중…";try{const info=await api("/settings/embedding-model-info",{method:"POST",body:JSON.stringify(embeddingValues())});const nativeDimension=Number(info.native_dimension);const options=dimensionOptions(nativeDimension);const current=Number(embeddingDimension.value||embeddingDimensionCustom.value);const selected=!useNative&&options.includes(current)?current:nativeDimension;embeddingDimension.innerHTML=options.map(value=>`<option value="${value}">${value}차원${value===nativeDimension?' (Ollama 기본·최대)':''}</option>`).join('');embeddingDimension.value=String(selected);embeddingDimensionCustom.value=String(selected);embeddingDimensionHelp.textContent=`Ollama 메타데이터: ${info.parameter_size?`${info.parameter_size} · `:''}기본·최대 ${nativeDimension}차원`;}catch(e){embeddingDimensionHelp.textContent=String(e);}finally{embeddingDimension.disabled=false;}};
  const refreshEmbeddingModels=async(useNative=false)=>{const previousModel=embeddingModel.value;embeddingSelect.disabled=true;embeddingSelect.innerHTML='<option value="">모델 목록을 불러오는 중…</option>';try{const r=await api("/settings/embedding-models",{method:"POST",body:JSON.stringify(embeddingValues())});setModelOptions(embeddingSelect,r.models,embeddingModel.value,embeddingModel);embeddingResult.textContent=`사용 가능한 임베딩 모델 ${r.models.length}개`;await refreshEmbeddingDimension(useNative||previousModel!==embeddingModel.value);}catch(e){embeddingSelect.innerHTML='<option value="">모델을 불러오지 못했습니다</option>';embeddingResult.textContent=String(e);}finally{embeddingSelect.disabled=false;}};
  embeddingProvider.onchange=()=>{embeddingBase.value=embeddingProvider.value==="ollama"?"http://127.0.0.1:11434/v1":embeddingProvider.value==="lmstudio"?"http://127.0.0.1:1234/v1":"";embeddingModel.value="";void refreshEmbeddingModels(true);};embeddingSelect.onchange=()=>{embeddingModel.value=embeddingSelect.value;void refreshEmbeddingDimension(true)};embeddingDimension.onchange=()=>{embeddingDimensionCustom.value=embeddingDimension.value};embeddingBase.onchange=()=>void refreshEmbeddingModels();document.querySelector<HTMLButtonElement>("#refresh-embedding-models")!.onclick=()=>void refreshEmbeddingModels();await refreshEmbeddingModels();
  document.querySelector<HTMLButtonElement>("#test-embedding")!.onclick=async()=>{try{const r=await api("/settings/test-embedding",{method:"POST",body:JSON.stringify(embeddingValues())});embeddingResult.textContent=`연결 성공 · ${h(r.dimension)}차원`;}catch(e){toast(String(e),true)}};
  const pollRebuild=async()=>{if(!document.querySelector("#embedding-result"))return;const state=await api("/settings/rebuild-embedding");embeddingResult.textContent=state.state==="running"?`새 데이터셋 생성 중 ${state.completed} / ${state.total}`:state.state==="complete"?"교체 완료 · 이전 데이터셋은 보관됩니다.":state.state==="failed"?`생성 실패 · 기존 모델 유지 · ${state.error}`:"";if(state.state==="running")window.setTimeout(()=>void pollRebuild(),1000);else if(state.state==="complete")void collection('model');};
  document.querySelector<HTMLButtonElement>("#replace-embedding")!.onclick=async()=>{if(!embeddingModel.value){toast("임베딩 모델을 선택하세요.",true);return;}const approved=await confirmAction("임베딩 데이터셋 생성 및 교체",`${embeddingModel.value} 데이터셋을 모두 만든 뒤 검색 모델을 교체합니다. 생성 중에는 현재 모델로 계속 검색합니다.`,"생성 시작");if(!approved)return;const button=document.querySelector<HTMLButtonElement>("#replace-embedding")!;button.disabled=true;button.textContent="생성 요청 중…";try{const result=await api("/settings/rebuild-embedding",{method:"POST",body:JSON.stringify(embeddingValues())});toast(result.reused?"보관된 데이터셋으로 즉시 전환했습니다.":"새 임베딩 데이터셋 생성을 시작했습니다.");await collection('model');}catch(e){button.disabled=false;button.textContent="데이터셋 생성 후 교체";toast(String(e),true)}};if(rebuild.state==="running")void pollRebuild();
  document.querySelectorAll<HTMLButtonElement>("[data-dataset-activate]").forEach(button=>button.onclick=async()=>{try{await api(`/settings/embedding-datasets/${button.dataset.datasetActivate}/activate`,{method:"PUT",body:JSON.stringify({api_key:embeddingKey.value||null})});toast("검색 데이터셋을 전환했습니다.");await collection('model');}catch(e){toast(String(e),true)}});
  document.querySelectorAll<HTMLButtonElement>("[data-dataset-sync]").forEach(button=>button.onclick=async()=>{try{await api(`/settings/embedding-datasets/${button.dataset.datasetSync}/sync`,{method:"POST",body:JSON.stringify({api_key:embeddingKey.value||null})});toast("데이터셋 동기화를 시작했습니다.");await collection('model');}catch(e){toast(String(e),true)}});
  document.querySelectorAll<HTMLButtonElement>("[data-dataset-delete]").forEach(button=>button.onclick=async()=>{const approved=await confirmAction("임베딩 데이터셋 삭제",`${button.dataset.datasetName} 임베딩 데이터만 삭제합니다. 원본 공지와 Ollama 모델 파일은 유지됩니다.`,"데이터 삭제");if(!approved)return;const previous=button.textContent;button.disabled=true;button.textContent="삭제 중…";try{const result=await api(`/settings/embedding-datasets/${button.dataset.datasetDelete}`,{method:"DELETE"});toast(`임베딩 청크 ${result.deleted_chunks}개를 삭제했습니다.`);await collection('model');}catch(e){button.disabled=false;button.textContent=previous;toast(String(e),true)}});
  if(rebuild.state!=="running"&&(datasetData.items||[]).some((item:any)=>item.status==="building"))window.setTimeout(()=>void collection('model'),1000);
}
function codexAccountMarkup(items:CodexAccount[]){return items.length?`<div class="account-grid">${items.map(a=>`<div class="account codex-account"><div><strong>${h(a.email||a.label)}</strong><span>${h(a.account_id||'계정 ID 없음')}</span></div><span class="account-status ${a.active?'active':''}">${a.active?'사용 중':'대기'}</span><button data-codex-select="${h(a.id)}" class="ghost" ${a.active?'disabled':''}>선택</button><button data-codex-remove="${h(a.id)}" class="danger">로그아웃</button></div>`).join('')}</div>`:'<div class="empty compact">Codex에 로그인된 계정이 없습니다.</div>'}
function bindCodexAccountButtons(){document.querySelectorAll<HTMLButtonElement>("[data-codex-select]").forEach(b=>b.onclick=async()=>{await api(`/auth/codex/accounts/${b.dataset.codexSelect}/select`,{method:"PUT"});toast("사용할 Codex 계정을 바꿨습니다.");collection('model')});document.querySelectorAll<HTMLButtonElement>("[data-codex-remove]").forEach(b=>b.onclick=async()=>{if(!confirm("이 장치의 KNU Server에서 Codex 계정을 로그아웃할까요?\nCodmes나 ChatGPT 계정은 영향받지 않습니다."))return;await api(`/auth/codex/accounts/${b.dataset.codexRemove}`,{method:"DELETE"});toast("계정을 로그아웃했습니다.");collection('model')});}
function setModelOptions(select:HTMLSelectElement,models:string[],current:string,input:HTMLInputElement=document.querySelector("#model-name") as HTMLInputElement){select.innerHTML=models.map(x=>`<option value="${h(x)}">${h(x)}</option>`).join('');if(models.includes(current))select.value=current;else if(models.length){select.value=models[0];input.value=models[0];}}
async function startCodexLogin(){try{const session=await api("/auth/codex/login",{method:"POST"});await invoke("open_auth_url",{url:session.verification_url});const state=document.querySelector("#login-state")!;state.innerHTML=`<div class="login-code"><div><span>브라우저에 아래 코드를 입력하세요</span><strong>${h(session.user_code)}</strong></div><button id="copy-code" class="ghost">코드 복사</button></div>`;document.querySelector<HTMLButtonElement>("#copy-code")!.onclick=async()=>{await navigator.clipboard.writeText(session.user_code);toast("코드를 복사했습니다.")};codexLoginTimer=window.setInterval(async()=>{try{const r=await api(`/auth/codex/login/${session.id}`);if(r.status==="approved"){clearInterval(codexLoginTimer!);codexLoginTimer=null;toast("Codex 로그인이 완료됐습니다.");collection('model')}else if(["error","expired","canceled"].includes(r.status)){clearInterval(codexLoginTimer!);codexLoginTimer=null;state.innerHTML=`<p class="error">${h(r.error||'로그인이 완료되지 않았습니다.')}</p>`;}}catch{}},Math.max(3000,session.interval*1000));}catch(e){toast(String(e),true)}}
async function collection(section: "crawl" | "model" = activeCollectionSection){stopViewPolling();activeCollectionSection=section;await (section==='crawl'?crawl():model());const view=document.querySelector<HTMLElement>("#view")!;view.insertAdjacentHTML('afterbegin',`<div class="section-tabs"><button data-collection-section="crawl" class="${section==='crawl'?'active':''}">수집 설정</button><button data-collection-section="model" class="${section==='model'?'active':''}">모델 설정</button></div>`);view.querySelectorAll<HTMLButtonElement>("[data-collection-section]").forEach(button=>button.onclick=()=>void collection(button.dataset.collectionSection as "crawl"|"model"));}
function crawlStatusLabel(status:string){return ({pending:"대기",listed:"목록 확인",processing:"상세 처리 중",ready:"LLM 정제 대기",stored:"원본 저장됨",refining:"LLM 정제 중",complete:"완료",complete_with_errors:"일부 실패",failed:"실패",stopped:"중지됨",interrupted:"비정상 종료로 중단됨",skipped:"저장됨",excluded:"범위 제외"} as Record<string,string>)[status]||status||"대기";}
function crawlRunView(settings:any,state:any){
  const run=state.run||{};const hasRun=Object.keys(run.sources||{}).length>0;const pending=Boolean(state.pending);const live=Boolean(state.active&&['running','paused'].includes(run.status));
  const total=Number(run.discovered||0),processed=Number(run.processed||0),failed=Number(run.failed||0),waiting=Math.max(0,total-processed);const percent=total?Math.min(100,Math.round(processed/total*100)):0;const acquired=Object.values(run.sources||{}).reduce((sum:number,source:any)=>sum+Number(source.saved||0),0);
  const paused=Boolean(state.paused||run.status==='paused'),stopping=Boolean(state.stop_requested);const canResume=Boolean(!state.active&&!pending&&hasRun&&(run.resumable||['interrupted','failed','stopped'].includes(run.status)));
  const phase=pending?'수집 시작 준비 중':stopping?'진행 중인 작업 취소 중':paused?'일시정지됨':live?(run.phase==='saved'?'저장 중':run.phase==='details'?'상세·첨부 처리 중':run.phase==='source'?`${run.source_name||run.source_code||'소스'} 준비 중`:'수집 준비 중'):run.status==='interrupted'?'비정상 종료로 중단됨':run.status==='failed'?'수집 실패':run.status==='stopped'?'사용자가 중지함':run.status==='complete'?'마지막 수집 완료':settings.crawl_enabled?'자동 수집 대기 중':'수동 수집 모드';
  const summary=hasRun?`${processed} / ${total} 처리 · ${acquired}건 원문 확보${canResume?' · 이어서 가능':''}`:'현재 진행 중인 수집 없음';
  const counts=hasRun?`처리 ${processed} · 대기 ${waiting} · 실패 ${failed}${run.error?` · ${run.error}`:run.current_title?` · 최근 처리 ${run.current_title}`:''}`:'수집을 시작하면 전체 진행률이 여기에 표시됩니다.';
  return {run,pending,live,total,processed,failed,waiting,percent,paused,stopping,canResume,phase,summary,counts};
}
function crawlSourceSummary(source:any){const total=Number(source.discovered||0),processed=Number(source.processed||0),saved=Number(source.saved||0),failed=Number(source.failed||0),percent=total?Math.round(processed/total*100):0;return `<button class="crawl-source-card ${activeNoticeSource===source.code?'selected':''}" data-crawl-source="${h(source.code)}"><span>${h(source.name||source.code)}</span><strong>${h(processed)} / ${h(total)}</strong><small>원문 확보 ${h(saved)} · 실패 ${h(failed)}</small><i><b style="width:${percent}%"></b></i></button>`;}
function crawlNoticeDetail(notice:any){const attachments=Object.values(notice.attachments||{}) as any[];return `<div class="notice-progress-detail"><div class="notice-stage"><span class="status-dot ${h(notice.status)}"></span><div><strong>${h(notice.stage||crawlStatusLabel(notice.status))}</strong>${notice.error?`<small>${h(notice.error)}</small>`:''}</div></div>${attachments.length?`<div class="attachment-progress"><h5>첨부파일 ${attachments.length}개</h5>${attachments.map(att=>`<div><span class="status-dot ${h(att.status)}"></span><strong>${h(att.name)}</strong><small>${h(att.stage||crawlStatusLabel(att.status))}${att.size?` · ${formatBytes(att.size)}`:''}${att.error?` · ${h(att.error)}`:''}</small></div>`).join('')}</div>`:'<p class="muted">첨부파일 없음</p>'}</div>`;}
function crawlSourceProgress(source:any,showSource:boolean){const pages=Object.values(source.pages||{}).sort((a:any,b:any)=>Number(a.page)-Number(b.page)) as any[];return `<div class="crawl-source-progress">${showSource?`<h4>${h(source.name||source.code)}</h4>`:''}<div class="crawl-page-list">${pages.map(page=>{const notices=Object.values(page.notices||{}) as any[];const done=notices.filter(n=>['complete','failed','skipped','excluded'].includes(n.status)).length;const pageKey=`${source.code}:${page.page}`;return `<details data-progress-page="${h(pageKey)}" ${page.status==='processing'||expandedProgressPages.has(pageKey)?'open':''}><summary><div><strong>${h(page.page)}페이지</strong><span>${notices.length}건 · ${done}/${notices.length} 처리 · 실패 ${h(page.failed||0)}</span></div><em>${h(crawlStatusLabel(page.status))}</em></summary><div class="crawl-notices">${notices.map(notice=>`<article class="crawl-notice ${h(notice.status)}"><span class="status-dot ${h(notice.status)}"></span><div><strong>${h(notice.title||'제목 확인 중')}</strong><small>${h(notice.stage||crawlStatusLabel(notice.status))}</small></div><div class="crawl-notice-actions">${notice.document_id?`<button class="text-link" data-notice="${h(notice.document_id)}">저장 데이터</button>`:''}<button class="text-link" data-progress-notice="${h(notice.url)}">${expandedProgressNotice===notice.url?'접기':'자세히 보기'}</button></div>${expandedProgressNotice===notice.url?crawlNoticeDetail(notice):''}</article>`).join('')}</div></details>`}).join('')}</div></div>`;}
function crawlProgressMarkup(run:any){const sources=Object.values(run?.sources||{}) as any[];if(!sources.length)return '';const selected=sources.find(source=>source.code===activeNoticeSource);const visibleSources=activeNoticeSource?(selected?[selected]:[]):sources;const badge=crawlStatusLabel(run.status==='running'?'processing':run.status);return `<section class="crawl-live panel"><div class="list-head"><div><h3>수집 현황</h3><p class="muted">비정상 종료 후에도 공지·첨부별 진행 목록을 유지합니다.</p></div><span class="live-badge ${h(run.status)}">${h(badge)}</span></div><div class="crawl-source-cards">${sources.map(crawlSourceSummary).join('')}</div>${visibleSources.length?visibleSources.map(source=>crawlSourceProgress(source,!activeNoticeSource)).join(''):'<div class="crawl-source-hint">수집 진행 정보가 아직 없습니다.</div>'}</section>`;}
async function notices(){
  stopViewPolling();
  const [filters,storage,crawlState]=await Promise.all([api("/notices/filters"),api("/notices/storage"),api("/crawl/status")]);
  let currentRun=crawlState.run||{};const runSources=Object.values(currentRun.sources||{}) as any[];const sourceMap=new Map<string,string>();filters.sources.forEach((x:any)=>sourceMap.set(x.code,x.name));runSources.forEach((x:any)=>sourceMap.set(x.code,x.name||x.code));
  if(activeNoticeSource&&!sourceMap.has(activeNoticeSource))activeNoticeSource="";
  if(!activeNoticeSource&&runSources.length===1)activeNoticeSource=runSources[0].code;
  const option=(value:string,label:string)=>`<option value="${h(value)}">${h(label)}</option>`;
  const sourceOptions=[...sourceMap.entries()].map(([code,name])=>option(code,name)).join('');
  document.querySelector("#view")!.innerHTML=`<div class="data-source-toolbar panel"><label>공지 구분<select id="notice-source"><option value="">전체 공지</option>${sourceOptions}</select></label><div><strong id="active-notice-source">${activeNoticeSource?h(sourceMap.get(activeNoticeSource)):"전체 공지"}</strong><small>수집 중인 항목과 저장 완료 데이터를 함께 조회합니다.</small></div></div><div id="crawl-live-root">${crawlProgressMarkup(currentRun)}</div><div class="data-storage panel"><div><span>전체 저장 용량</span><strong id="storage-bytes">${formatBytes(storage.bytes)}</strong></div><small id="storage-summary">공지 ${h(storage.notice_count)}건 · 자산 ${h(storage.asset_count)}개 · DB ${formatBytes(storage.database_bytes)} · 파일 ${formatBytes(storage.asset_file_bytes)}</small></div><div class="notice-filters panel"><div class="filter-grid"><label>카테고리<select id="notice-category"><option value="">전체 카테고리</option>${filters.categories.map((x:string)=>option(x,x)).join('')}</select></label><label class="date-filter">날짜<span class="date-range"><input id="notice-from" type="date" aria-label="시작일"/><i>–</i><input id="notice-to" type="date" aria-label="종료일"/></span></label><label>공지 상태<select id="notice-archive"><option value="all">전체</option><option value="active">현재 공지</option><option value="archived">과거 공지</option></select></label><label>추출 버전<select id="notice-version"><option value="">전체 버전</option>${filters.extraction_versions.map((x:string)=>option(x,x)).join('')}</select></label><label class="search-field">검색<input id="notice-search" placeholder="제목·본문 검색"/></label></div></div><div class="split"><article class="panel list"><div class="list-head"><h3 id="notice-count">저장된 공지</h3><button id="reset-notice-filters" class="ghost">필터 초기화</button></div><div id="notice-list"><div class="loading">불러오는 중…</div></div></article><article id="notice-detail" class="panel detail"><div class="empty">왼쪽에서 공지를 선택하세요.</div></article></div>`;
  const sourceSelect=document.querySelector<HTMLSelectElement>("#notice-source")!;sourceSelect.value=activeNoticeSource;
  const ids=['notice-category','notice-from','notice-to','notice-archive','notice-version','notice-search'] as const;
  const inputs=Object.fromEntries(ids.map(id=>[id,document.querySelector<HTMLInputElement|HTMLSelectElement>(`#${id}`)!])) as Record<typeof ids[number],HTMLInputElement|HTMLSelectElement>;
  inputs['notice-category'].value=noticeFilterState.category;inputs['notice-from'].value=noticeFilterState.from;inputs['notice-to'].value=noticeFilterState.to;inputs['notice-archive'].value=noticeFilterState.archive;inputs['notice-version'].value=noticeFilterState.version;inputs['notice-search'].value=noticeFilterState.search;
  const syncFilterState=()=>{noticeFilterState.category=inputs['notice-category'].value;noticeFilterState.from=inputs['notice-from'].value;noticeFilterState.to=inputs['notice-to'].value;noticeFilterState.archive=inputs['notice-archive'].value;noticeFilterState.version=inputs['notice-version'].value;noticeFilterState.search=inputs['notice-search'].value;};
  const row=(n:Notice)=>`<button data-notice="${n.id}"><strong>${h(n.title)}</strong><span>${h(n.source)} · ${h(n.posted_at||'날짜 없음')} · ${h(n.category)} · ${n.archived_at?'과거 공지':'현재 공지'} · 추출 ${h(n.extraction_version||'버전 없음')} · 임베딩 ${h((n.embedding_models||[]).join(', ')||'없음')} · ${formatBytes(n.storage_bytes)}</span></button>`;
  const load=async()=>{syncFilterState();const params=new URLSearchParams({limit:'100',q:noticeFilterState.search,source_code:activeNoticeSource,category:noticeFilterState.category,archive:noticeFilterState.archive,extraction_version:noticeFilterState.version});if(noticeFilterState.from)params.set('date_from',noticeFilterState.from);if(noticeFilterState.to)params.set('date_to',noticeFilterState.to);const result=await api(`/notices?${params}`);document.querySelector("#notice-count")!.textContent=`저장된 공지 ${result.total}건`;const box=document.querySelector("#notice-list")!;box.innerHTML=result.items.length?result.items.map(row).join(''):'<div class="empty compact">조건에 맞는 공지가 없습니다.</div>';box.querySelectorAll<HTMLButtonElement>("[data-notice]").forEach(button=>button.onclick=()=>showNotice(Number(button.dataset.notice)));};
  const updateStorage=async()=>{const next=await api("/notices/storage");document.querySelector("#storage-bytes")!.textContent=formatBytes(next.bytes);document.querySelector("#storage-summary")!.textContent=`공지 ${next.notice_count}건 · 자산 ${next.asset_count}개 · DB ${formatBytes(next.database_bytes)} · 파일 ${formatBytes(next.asset_file_bytes)}`;};
  const renderProgress=()=>{const root=document.querySelector<HTMLElement>("#crawl-live-root")!;root.innerHTML=crawlProgressMarkup(currentRun);root.querySelectorAll<HTMLButtonElement>("[data-crawl-source]").forEach(button=>button.onclick=()=>{activeNoticeSource=button.dataset.crawlSource||"";expandedProgressNotice="";sourceSelect.value=activeNoticeSource;document.querySelector("#active-notice-source")!.textContent=sourceMap.get(activeNoticeSource)||"전체 공지";renderProgress();void load()});root.querySelectorAll<HTMLButtonElement>("[data-progress-notice]").forEach(button=>button.onclick=()=>{expandedProgressNotice=expandedProgressNotice===button.dataset.progressNotice?"":button.dataset.progressNotice||"";renderProgress()});root.querySelectorAll<HTMLDetailsElement>("[data-progress-page]").forEach(details=>details.ontoggle=()=>{const key=details.dataset.progressPage||"";if(details.open)expandedProgressPages.add(key);else expandedProgressPages.delete(key)});root.querySelectorAll<HTMLButtonElement>("[data-notice]").forEach(button=>button.onclick=()=>showNotice(Number(button.dataset.notice)));};
  sourceSelect.onchange=()=>{activeNoticeSource=sourceSelect.value;expandedProgressNotice="";document.querySelector("#active-notice-source")!.textContent=sourceMap.get(activeNoticeSource)||"전체 공지";renderProgress();void load()};
  renderProgress();
  let timer:number;Object.values(inputs).forEach(input=>{input.onchange=()=>void load()});inputs['notice-search'].oninput=()=>{clearTimeout(timer);timer=window.setTimeout(()=>void load(),250)};
  document.querySelector<HTMLButtonElement>("#reset-notice-filters")!.onclick=()=>{Object.assign(noticeFilterState,{category:"",from:"",to:"",archive:"all",version:"",search:""});inputs['notice-category'].value="";inputs['notice-from'].value="";inputs['notice-to'].value="";inputs['notice-archive'].value="all";inputs['notice-version'].value="";inputs['notice-search'].value="";void load()};
  await load();
  if(selectedNotice)await showNotice(selectedNotice).catch(()=>{selectedNotice=null});
  let progressSignature=JSON.stringify(currentRun);let savedCount=Number(currentRun.saved||0);
  const refreshProgress=async()=>{try{const next=await api("/crawl/status");if(!document.querySelector("#crawl-live-root"))return;currentRun=next.run||{};const signature=JSON.stringify(currentRun);if(signature!==progressSignature){progressSignature=signature;renderProgress()}const nextSaved=Number(currentRun.saved||0);if(nextSaved!==savedCount){savedCount=nextSaved;await Promise.all([updateStorage(),load()])}if(next.active||next.pending)pollView(()=>void refreshProgress(),1000)}catch{if(document.querySelector("#crawl-live-root"))pollView(()=>void refreshProgress(),2000)}};
  if(crawlState.active||crawlState.pending)pollView(()=>void refreshProgress(),1000);
}
const documentInternalKinds=new Set(["attachment_hwp_structure","attachment_hwp_markdown","attachment_hwp_validation","attachment_hwp_image","attachment_hwp_binary","attachment_document_image","inline_image"]);
function attachmentMarkup(asset:Asset){return `<details><summary>${h(asset.filename||asset.kind)}</summary><pre>${h(asset.extracted_text||'추출 텍스트 없음')}</pre>${asset.source_url?`<button class="text-link" data-external-url="${h(asset.source_url)}">첨부 원본 열기</button>`:''}</details>`;}
function qualityMarkup(asset:Asset|undefined){if(!asset)return '<p class="muted">구조·품질 정보 없음</p>';try{const value=JSON.parse(asset.extracted_text||'{}');return `<dl class="quality-grid"><dt>판정</dt><dd>${h(value.status||'없음')}</dd><dt>품질 점수</dt><dd>${value.score==null?'없음':h(Math.round(Number(value.score)*1000)/10+'%')}</dd><dt>본문 일치도</dt><dd>${value.textTokenF1==null?'없음':h(Math.round(Number(value.textTokenF1)*1000)/10+'%')}</dd><dt>표</dt><dd>${h(value.tableCount??0)}개 · 셀 ${h(value.tableCellCount??0)}개</dd></dl>`;}catch{return `<pre>${h(asset.extracted_text||'품질 정보 없음')}</pre>`;}}
function documentAnalysisMarkup(assets:Asset[]){if(!assets.length)return '';const structure=assets.find(a=>a.kind==="attachment_hwp_structure");const markdown=assets.some(a=>a.kind==="attachment_hwp_markdown");const validation=assets.some(a=>a.kind==="attachment_hwp_validation");const images=assets.filter(a=>a.kind==="attachment_hwp_image"||a.kind==="attachment_document_image"||a.kind==="inline_image").sort((a,b)=>Number(a.extra?.figure?.number??999)-Number(b.extra?.figure?.number??999));const binaries=assets.filter(a=>a.kind==="attachment_hwp_binary");return `<details class="processing-results"><summary>본문·문서 그림 처리 상세 · 내부 파일 ${assets.length}개</summary><p class="muted">공지 본문과 HWP·HWPX·PDF·Word·Excel·PowerPoint의 검증된 그림 설명만 번호와 문맥을 포함해 검색에 사용합니다.</p>${structure?qualityMarkup(structure):''}${structure?`<div class="process-flags"><span>${markdown?'✓':'—'} 검색용 Markdown</span><span>${validation?'✓':'—'} HWPX 교차 검증</span></div>`:''}${images.length?`<h4>본문·문서 그림 ${images.length}개</h4><div class="asset-images">${images.map(a=>{const figure=a.extra?.figure;const analysis=a.extra?.analysis;const label=figure?.label||a.filename||'문서 내부 이미지';return `<figure><div class="asset-preview"><span>미리보기 불러오는 중…</span><img data-asset-preview="${a.id}" alt="${h(label)}"/></div><figcaption><strong>${h(label)} · ${h(a.filename)}</strong><span>${h(analysis?.description||'이미지 설명은 아직 생성되지 않았습니다.')}</span>${figure?.context?`<details class="image-context"><summary>문서 내 위치</summary><span>${h(figure.context)}</span></details>`:''}</figcaption></figure>`}).join('')}</div>`:''}${binaries.length?`<p class="muted">기타 내부 바이너리 ${binaries.length}개</p>`:''}</details>`;}
async function loadAssetPreviews(){await Promise.all([...document.querySelectorAll<HTMLImageElement>("[data-asset-preview]")].map(async img=>{try{const blob=await apiBlob(`/assets/${img.dataset.assetPreview}/content`);const url=URL.createObjectURL(blob);assetObjectUrls.push(url);img.src=url;img.onload=()=>img.parentElement?.classList.add("loaded");}catch{img.alt="이미지 미리보기를 불러오지 못했습니다.";img.parentElement?.classList.add("failed");}}));}
async function showNotice(id:number){ selectedNotice=id; assetObjectUrls.forEach(URL.revokeObjectURL);assetObjectUrls=[]; const n=await api(`/notices/${id}`);const assets:Asset[]=n.assets||[];const attachments=assets.filter(a=>!documentInternalKinds.has(a.kind));const internal=assets.filter(a=>documentInternalKinds.has(a.kind)); const el=document.querySelector("#notice-detail")!; el.innerHTML=`<span class="eyebrow">${h(n.source)} · ${h(n.category)}</span><h2>${h(n.title)}</h2><div class="metadata"><span>게시 ${h(n.posted_at)}</span><span>추출 버전 ${h(n.extraction_version||'없음')}</span><span>임베딩 모델 ${h((n.embedding_models||[]).join(', ')||'없음')}</span><span>추출 신뢰도 ${n.extraction_confidence==null?'없음':Math.round(n.extraction_confidence*100)+'%'}</span><span>용량 ${formatBytes(n.storage_bytes)}</span><button id="open-original" class="text-link">원문</button></div><h3>저장된 본문</h3><div class="stored-body">${richText(n.body_content||n.content||'본문 없음')}</div><h3>첨부파일 ${attachments.length?attachments.length+'개':''}</h3>${attachments.length?attachments.map(attachmentMarkup).join(''):'<p class="muted">첨부 없음</p>'}${documentAnalysisMarkup(internal)}`; document.querySelector<HTMLButtonElement>("#open-original")!.onclick=()=>openExternal(n.url);document.querySelectorAll<HTMLButtonElement>("[data-external-url]").forEach(button=>button.onclick=()=>openExternal(button.dataset.externalUrl!));await loadAssetPreviews(); }
async function openExternal(url:string){try{await invoke("open_external_url",{url});}catch(error){toast(String(error),true)}}
async function accounts(){ const d=await api("/accounts"); document.querySelector("#view")!.innerHTML=`<article class="panel"><div class="list-head"><h3>가입 계정 ${d.items.length}개</h3><span class="muted">공식 포털 비밀번호는 저장하거나 변경하지 않습니다.</span></div><div class="account-grid">${d.items.map((a:Account)=>`<div class="account"><div><strong>${h(a.username)}</strong><span>${h(a.email||'이메일 없음')}</span></div><div><span>${h(a.student_id||'포털 미연결')}</span><span>${h(a.major||'학과 없음')} ${a.year?`${a.year}학년`:''}</span></div><button data-edit="${a.id}" class="ghost">수정</button><button data-delete="${a.id}" class="danger">삭제</button></div>`).join('')}</div></article>`; const map=new Map<number,Account>(d.items.map((a:Account)=>[a.id,a])); document.querySelectorAll<HTMLButtonElement>("[data-edit]").forEach(b=>b.onclick=()=>editAccount(map.get(Number(b.dataset.edit))!)); document.querySelectorAll<HTMLButtonElement>("[data-delete]").forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.delete);if(!confirm("KNU 서비스 계정을 삭제할까요? 공주대 공식 포털 계정은 삭제되지 않습니다."))return;const linked=confirm("연결된 학적·시간표·LMS 데이터도 함께 삭제할까요?\n취소를 누르면 서비스 계정만 삭제합니다.");await api(`/accounts/${id}?delete_linked_data=${linked}`,{method:"DELETE"});toast("계정을 삭제했습니다.");accounts();}); }
function editAccount(a:Account){ const dialog=document.createElement("dialog"); dialog.innerHTML=`<form method="dialog" class="form"><h3>계정 수정</h3>${[["username","사용자명",a.username],["email","이메일",a.email],["student_id","학번",a.student_id],["name","이름",a.name],["major","학과",a.major],["year","학년",a.year]].map(([id,l,v])=>`<label>${l}<input id="e-${id}" value="${h(v)}"/></label>`).join('')}<div class="actions"><button value="cancel" class="ghost">취소</button><button id="edit-save" value="default">저장</button></div></form>`;document.body.append(dialog);dialog.showModal();dialog.querySelector<HTMLButtonElement>("#edit-save")!.onclick=async e=>{e.preventDefault();const val=(id:string)=>(dialog.querySelector(`#e-${id}`) as HTMLInputElement).value||null;await api(`/accounts/${a.id}`,{method:"PUT",body:JSON.stringify({username:val("username"),email:val("email"),student_id:val("student_id"),name:val("name"),major:val("major"),year:val("year")?Number(val("year")):null})});dialog.close();dialog.remove();toast("계정을 수정했습니다.");accounts();};dialog.onclose=()=>dialog.remove(); }
async function logs(){ await refreshRuntime(); document.querySelector("#view")!.innerHTML=`<article class="panel"><div class="list-head"><h3>최근 로그</h3><button id="clear-logs" class="ghost">비우기</button></div><pre class="logs">${h(runtime.logs.join('\n')||'아직 로그가 없습니다.')}</pre></article>`; document.querySelector<HTMLButtonElement>("#clear-logs")!.onclick=async()=>{await invoke("clear_logs");logs();}; }

async function crawl(){
  const [s,state]=await Promise.all([api("/settings"),api("/crawl/status")]);
  const sources=s.capabilities?.crawl_sources||[]; const saved=s.crawl_request||{};
  const selectedSources=new Set(saved.source_codes?.length?saved.source_codes:sources.map((source:any)=>source.code));
  const locked=Boolean(s.crawl_enabled||state.active||state.pending);
  const initial=crawlRunView(s,state);const {run,paused,stopping,canResume}=initial;
  document.querySelector("#view")!.innerHTML=`<article class="panel form crawl-settings"><div class="crawl-heading"><div><h3>수집 설정</h3><p class="muted">수동·자동 수집이 같은 범위와 소스, 추출 규칙을 사용합니다.</p></div><label class="toggle compact"><em>자동 수집</em><input id="crawl-enabled" type="checkbox" ${s.crawl_enabled?'checked':''}/><span></span><strong>${s.crawl_enabled?'ON':'OFF'}</strong></label></div><div class="crawl-state"><span id="crawl-phase">${h(initial.phase)}</span><strong id="crawl-summary">${h(initial.summary)}</strong><small id="crawl-counts">${h(initial.counts)}</small>${state.active?`<div class="crawl-progress"><i id="crawl-progress-bar" style="width:${initial.percent}%"></i></div><div class="crawl-controls"><button id="pause-crawl" class="ghost" ${stopping?'disabled':''}>${paused?'수집 재개':'일시정지'}</button><button id="stop-crawl" class="danger" ${stopping?'disabled':''}>${stopping?'중지 중…':'수집 중지'}</button></div>`:''}</div>${locked?`<div class="crawl-lock">${s.crawl_enabled?'자동 수집이 켜져 있어 설정이 잠겼습니다. 수집 설정을 바꾸려면 자동 수집을 끄세요.':'현재 수집이 끝날 때까지 설정을 바꿀 수 없습니다.'}</div>`:''}<fieldset ${locked?'disabled':''}><label>수집 방식<select id="crawl-mode"><option value="all">전체 페이지</option><option value="range">지정 페이지 범위</option><option value="recent">최근 7일</option></select></label><div id="page-fields" class="page-fields"><label>시작 페이지<input id="start-page" type="number" min="1" value="${h(saved.start_page||1)}"/></label><label>끝 페이지<input id="end-page" type="number" min="1" value="${h(saved.end_page||saved.start_page||1)}"/></label></div><div><strong class="field-title">자동 수집 주기</strong><div class="segments">${[1,6,12,24].map(x=>`<button type="button" data-hours="${x}" class="${s.crawl_interval_hours===x?'selected':''}">${x===24?'1일':x+'시간'}</button>`).join('')}</div></div><label class="check refresh-version"><input id="refresh-extraction" type="checkbox" ${saved.refresh_outdated_extraction?'checked':''}/><span>이전 추출 버전도 ${h(s.capabilities?.current_extraction_version||'현재 버전')}로 갱신<small>체크하지 않으면 완료된 이전 버전 공지는 그대로 둡니다.</small></span></label><div><strong class="field-title">수집 소스</strong><div class="source-grid">${sources.map((source:any)=>`<label class="check"><input type="checkbox" data-source="${h(source.code)}" ${selectedSources.has(source.code)?'checked':''}/><span>${h(source.name)}${source.paged?'':' · 단일 문서'}</span></label>`).join('')}</div></div><p class="muted">본문·첨부 수집이 끝난 공지는 즉시 체크포인트로 보존하고, LLM 정제 후 최종 데이터로 저장합니다. 중단되면 보존된 다음 단계부터 이어집니다.</p><div class="actions"><button id="run-now">수집 시작</button></div></fieldset></article>`;
  let interval=s.crawl_interval_hours; const mode=document.querySelector<HTMLSelectElement>("#crawl-mode")!; const fields=document.querySelector<HTMLElement>("#page-fields")!; const start=document.querySelector<HTMLInputElement>("#start-page")!; const end=document.querySelector<HTMLInputElement>("#end-page")!;
  mode.value=saved.mode||'all'; const updatePageFields=()=>fields.hidden=mode.value!=='range'; mode.onchange=updatePageFields; updatePageFields();
  document.querySelectorAll<HTMLButtonElement>("[data-hours]").forEach(b=>b.onclick=()=>{interval=Number(b.dataset.hours);document.querySelectorAll("[data-hours]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});
  const request=()=>({mode:mode.value,start_page:Number(start.value),end_page:mode.value==='range'?Number(end.value):null,recent_days:7,refresh_outdated_extraction:document.querySelector<HTMLInputElement>("#refresh-extraction")!.checked,source_codes:[...document.querySelectorAll<HTMLInputElement>("[data-source]:checked")].map(x=>x.dataset.source!)});
  const save=async(crawl_enabled:boolean)=>api("/settings",{method:"PUT",body:JSON.stringify({crawl_enabled,crawl_interval_hours:interval,crawl_request:request(),vlm:{...s.vlm,api_key:null}})});
  const enabled=document.querySelector<HTMLInputElement>("#crawl-enabled")!; const enabledLabel=enabled.parentElement!.querySelector("strong")!; enabled.disabled=(state.active||state.pending)&&!s.crawl_enabled;
  enabled.onchange=async()=>{const next=enabled.checked;enabled.disabled=true;try{if(next&&!request().source_codes.length)throw new Error("수집 소스를 하나 이상 선택하세요.");await save(next);enabledLabel.textContent=next?'ON':'OFF';toast(`자동 수집을 ${next?'켰습니다':'껐습니다'}.`);await collection('crawl');}catch(e){enabled.checked=!next;toast(String(e),true);enabled.disabled=false;}};
  document.querySelector<HTMLButtonElement>("#run-now")!.onclick=async()=>{try{const value=request();if(!value.source_codes.length){toast("수집 소스를 하나 이상 선택하세요.",true);return;}await save(false);await api("/crawl/run",{method:"POST",body:JSON.stringify(value)});toast("공지 수집을 시작했습니다.");await collection('crawl');}catch(e){toast(String(e),true)}};
  const pauseButton=document.querySelector<HTMLButtonElement>("#pause-crawl");if(pauseButton)pauseButton.onclick=async()=>{try{await api(paused?"/crawl/resume":"/crawl/pause",{method:"POST"});toast(paused?"공지 수집을 재개합니다.":"현재 작업을 일시정지합니다.");await collection('crawl');}catch(e){toast(String(e),true)}};
  const stopButton=document.querySelector<HTMLButtonElement>("#stop-crawl");if(stopButton)stopButton.onclick=async()=>{try{await api("/crawl/stop",{method:"POST"});toast("진행 중인 작업을 취소하고 체크포인트를 보존합니다.");await collection('crawl');}catch(e){toast(String(e),true)}};
  if(canResume&&!state.active){const resume=document.createElement("button");resume.id="retry-crawl";resume.textContent="이어서 수집";document.querySelector(".crawl-state")!.append(resume);resume.onclick=async()=>{try{resume.disabled=true;resume.textContent="재개 요청 중…";await api("/crawl/retry",{method:"POST"});toast("DB에 저장된 미완료 단계부터 이어서 처리합니다.");await collection('crawl');}catch(e){resume.disabled=false;resume.textContent="이어서 수집";toast(String(e),true)}};const detail=document.createElement("button");detail.className="ghost";detail.textContent="목록 자세히 보기";document.querySelector(".crawl-state")!.append(detail);detail.onclick=()=>void openTab("notices")}
  let pollState=state;const refreshCrawlState=async()=>{try{const next=await api("/crawl/status");if(!document.querySelector("#crawl-summary"))return;if(Boolean(next.active)!==Boolean(pollState.active)||Boolean(next.pending)!==Boolean(pollState.pending)||Boolean(next.paused)!==Boolean(pollState.paused)||Boolean(next.stop_requested)!==Boolean(pollState.stop_requested)){await collection('crawl');return}pollState=next;const value=crawlRunView(s,next);document.querySelector("#crawl-phase")!.textContent=value.phase;document.querySelector("#crawl-summary")!.textContent=value.summary;document.querySelector("#crawl-counts")!.textContent=value.counts;const bar=document.querySelector<HTMLElement>("#crawl-progress-bar");if(bar)bar.style.width=`${value.percent}%`;if(next.active||next.pending)pollView(()=>void refreshCrawlState(),1000)}catch{if(document.querySelector("#crawl-summary"))pollView(()=>void refreshCrawlState(),2000)}};if(state.active||state.pending)pollView(()=>void refreshCrawlState(),1000);
}

shell(); refreshRuntime().then(()=>openTab("dashboard")); setInterval(()=>refreshRuntime().catch(()=>{}),4000);
